### PR TITLE
ClientApplication external auth

### PR DESCRIPTION
**Pull request by codyebberson**
Fixes https://github.com/medplum/medplum/issues/1417

### CODE REVIEW

**Review by rahul1 — APPROVED** [review]

**Comment by reshmakh** [comment]
This looks very sensible and cool.  The only question I have is that should we check whether this is coming from a registered domain?

**Comment by reshmakh** [comment]
Perhaps require that it be launched from registered domain or launch URI (or localhost)?

**Comment by codyebberson** [comment]
> Perhaps require that it be launched from registered domain or launch URI (or localhost)?

Yeah... there are 3 TODO's in the current commit that are all about validation.  This commit demonstrates end to end working example.  I need to add tests and safeguards.

**Comment by reshmakh** [comment]
This needs to be documented as part of #1467

**Pull request merged**
