### PR TITLE
[WIP] Bot Debugger Using Sandpack

### PR DESCRIPTION
**Pull request by rahul1**
This PR modifies the Bot code editor to create a fully client-side execution environment to debug bots. 

- Users write a single `handler(medplum, event)` function, exactly the same as with AWS Lambda Bots
- A `MedplumClient` is initialized by the wrapper code and passed into the handler
- Compilation errors are detected continuously
- When the user clicks `Execute`, the handler is run
- The user can optionally specify data input to the `handler` in the `input.ts` file
- Clicking "Save" saves the handler code to the server
- Clicking "Publish" pushes code the to the same endpoint as before for `AWS Lambda Bots`

Sandpack

Remaining Items:
- [ ] Fix CORs issues for `MedplumClient` auth
- [ ] Host our own version of the sandpack bundler
- [ ] Autocomplete

### CODE REVIEW

**Comment by codyebberson** [comment]
Yay!  This is exciting!

Looking... 👀

**Comment by rahul1** [comment]
To build the sandpack bundler yourself. 

```zsh
git clone git@github.com:codesandbox/codesandbox-client.git
cd codesandbox-client
eval "$(fnm env --use-on-cd)"
fnm use.  #Using Node v10.23.2
yarn install
yarn build:deps
yarn build:sandpack

cd www
```

**Comment by codyebberson** [comment]
@rahul1  For discussion.... Codesandbox requires `unsafe-eval`, which is going to be an issue for security.  

We may be able to use `hash="..."` or `nonce="..."`.

image

**Comment by codyebberson** [comment]
@rahul1 Update:

1. Deployed `codesandbox-client` to https://codesandbox.medplum.com
2. Updated `<CodeEditor>` to use that URL
3. Deployed to https://app.staging.medplum.com
4. Executes with no errors or warnings!

However:

1. The editor is buggy.  It gets into a bad state where you can't edit.  Might be caching problem?
2. Still lots of requests to external domains
  a. data.jsdelivr.com - looks like pre-built npm dependencies, probably fine
  b. prod-packager-packages.codesandbox.io - looks like pre-built npm dependencies, probably fine
  c. col.csbops.io - looks like analytics?  need to investigate

I'll continue investigating.

**Comment by codyebberson** [comment]
This is superseded by https://github.com/medplum/medplum/pull/584

**Pull request closed without merging**
