### PR TITLE
Updating documentation structure for review

### PR DESCRIPTION
**Pull request by reshmakh**
This one is a proposed restructure of the site documentation that is more aligned with technical documentation on other sites.  Mapping the new structure back to the Diataxis framework, I propose the following:

Documentation.Quickstart = Tutorials
Documentation.<Product>.index = Exploration
Documentation.<Product>.<other-file> = How-To-Guides
Reference = Reference

### CODE REVIEW

**Comment by reshmakh** [comment]
Updated broken links post refactor and have a new (more direct) mapping outlined below:

Documentation.Tutorials = Tutorials
Documentation.[directory].index = Explanation
Documentation.[directory].* = How-To-Guides
Reference = Reference

**Review by codyebberson — APPROVED** [review]
Amazing!

**Review by im2nguyen — COMMENTED** [review]
i think this is a great step in the right direction! a couple of nits but overall good 😄 

one thing i would recommend (but not sure if possible) is grouping some of the pages together. for example:

Get Started
 - Welcome to Medplum
 - FHIR Basics
 - Tutorials
 - MedPlum App

Core Workflows:
- Auth and Identity
- Care Plans
- Questionnaires
- Scheduling
- Medications
- Charting
- Comms and Messaging
- Billing and Payments

Automation:
- Subscriptions
- Bots

Reference:
- FHIR Datastore
- React UI Components

Advanced
- Integrations
- Self-Hosting
- Compliance

**Comment by reshmakh** [comment]
Thanks so much @im2nguyen!  I have addressed most of your feedback.  Another nit: @rahul1 - these side nav down arrows for the top level are a little visually distracting.  I'm not sure if there is a way to remove those

image

**Pull request merged**
