### PR TITLE
Task/change server port 5000 to 8103

### PR DESCRIPTION
**Pull request by brandonin**
port 5000 is used by mission control on the newer versions of macOS. 8xxx is a more standard developer port for most NodeJS applications. There is an open question on if this changes any infrastructure settings that are manually inputted as it does change the Dockerfile.

I've tested this on my local machine and it works as expected.

### CODE REVIEW

**Comment by codyebberson** [comment]
Thanks for submitting @brandonin !

> 8xxx is a more standard developer port for most NodeJS applications. There is an open question on if this changes any infrastructure settings that are manually inputted as it does change the Dockerfile.

I'm broadly supportive of making a change like this.  I'll discuss specifics with the team on Monday.  Two considerations that we'll discuss:

1. If we're going to make a change, let's change it to something that is unlikely to have collisions.  Port 8000 is the default for a number of other tools, such as Python's http.server utility.  So maybe choosing a port number more off the beaten path.
2. We will probably need to make this a config setting, at least in the server project, so we can continue using port 5000 in our production infra.

I really appreciate the submission.  We'll get feedback soon.  Thank you!

**Review by codyebberson — CHANGES_REQUESTED** [review]
Hi @brandonin 

We had a chance to review more in-depth.  Our primary consideration was future-proofing, so that if we make a change, we minimize the chance of needing to change again.  We also want to build toward a cohesive port strategy for all running services (app, server, storybook, docusaurus).

We landed on choosing ports in the 8103-8110 block.  These appear to be relatively clean in the 8000 block:
- https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
- https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

Would you like to make the change to 8103?  We're happy to do it as well.

Thanks again!

**Comment by brandonin** [comment]
@codyebberson done.

**Comment by brandonin** [comment]
Let me know if I could be of more help.

**Comment by codyebberson** [comment]
> @codyebberson done.

Great, thank you!  This is great.  I'm going to hold this for a bit until we prep the prod implications, but we'll get it out soon.

Thank you!

**Comment by codyebberson** [comment]
Completed with https://github.com/medplum/medplum/pull/801

**Pull request closed without merging**
