### PR TITLE
Add stories for US Core Patient Profile and Implantable Device

### PR DESCRIPTION
**Pull request by mattlong**

### CODE REVIEW

**Comment by mattlong** [comment]
Related to #3592

**Comment by codyebberson** [comment]
FYI - Sonar can't differentiate between URL as an identifier vs URL as a request target.  You can sign into Sonar and mark them as "Safe":

image

image


I've wondered if we should have a single constant somewhere in `@medplum/core` for "http://hl7.org", which we could then refer to everywhere to avoid all the false positives.  It would be kinda clunky, but perhaps less clunky than overriding.

**Review by codyebberson — APPROVED** [review]
Nice https://medplum-storybook-git-uscore-stories-medplum.vercel.app/?path=%2Fstory%2Fmedplum-resourceform--us-core-patient

**Comment by reshmakh** [comment]
Very cool!

**Comment by mattlong** [comment]
> I've wondered if we should have a single constant somewhere in `@medplum/core` for "http://hl7.org", which we could then refer to everywhere to avoid all the false positives. It would be kinda clunky, but perhaps less clunky than overriding.

I added it; it does indeed feel a little clunky, but better than the false-positives I'd say.

**Pull request merged**
