### PR TITLE
Add Extension to Bot resource

### LINKED ISSUE #4473: Bot resource missing Extension
Was there a design reason that the Bot resource does not support an Extension? With the addition of [https://github.com/medplum/medplum/pull/4324](https://github.com/medplum/medplum/pull/4324) with the Bot reference on the Event, it would allow adding Bot specific config via Extensions instead of needing Project secrets for config values.

### PR DESCRIPTION
**Pull request by jmalobicky**
Fixes #4473 

Having an issue fixing the below on the Timeline view.
image

### CODE REVIEW

**Comment by jmalobicky** [comment]
@rahul1 @ThatOneBro Any help on how to resolve the Timeline display issue?

**Comment by codyebberson** [comment]
Thanks @jmalobicky 

For context:

FHIR resources can "extend" either [`Resource`](https://hl7.org/fhir/R4/resource.html) or [`DomainResource`](https://hl7.org/fhir/R4/domainresource.html) (`DomainResource` extends `Resource`).

`extension` is defined on `DomainResource` but not `Resource`

It looks like when we wrote the original `Bot` `StructureDefinition`, we extended `Resource`, not `DomainResource`.

As @mattwiller pointed out:

> This resource extends the base Resource. All of the listed Resources except Bundle, Parameters and Binary extend this resource.

So, it seems like it’s the rule with few exceptions.

I support this change, but I think we should go all the way and add all of the `DomainResource` elements (`text`, `contained`, `extension`, and `modifierExtension`).

**Comment by jmalobicky** [comment]
Thanks for the context. Let me see if I can make those changes.

**Comment by codyebberson** [comment]
Whoops!  Had already started on this!  Feel free to reject

**Comment by jmalobicky** [comment]
You are good. You know way more about this space than I do.

**Review by ThatOneBro — APPROVED** [review]

**Pull request merged**
