### PR TITLE
FHIR Search Guide

### PR DESCRIPTION
**Pull request by rahul1**
Our existing guide on FHIR search was too basic (and not visible in the navbar). A lot of our users still had  questions about some of the basics of making FHIR queries, so I wrote this guide to explain some key concepts: 
1. Search Parameters
2. Making Searches
3. Search Modifiers
4. Search Prefixes

### CODE REVIEW

**Review by tonylee80 — APPROVED** [review]
Looks good! I like the improved search document from current: https://www.medplum.com/docs/fhir-datastore/basic-fhir-search vs the new version on vercel preview: https://medplum-www-git-rahul-search-pages-medplum.vercel.app/docs/search/basic-search.

**Comment by codyebberson** [comment]
@rahul1 - How do you think about this being peer with "FHIR Datastore" vs being a child of "FHIR Datastore"?

**Comment by codyebberson** [comment]
Direct link to new doc: https://medplum-www-git-rahul-search-pages-medplum.vercel.app/docs/search/basic-search

**Review by jamestouri — APPROVED** [review]

**Comment by rahul1** [comment]
@codyebberson I see your logic, but I was trying to follow our product ontology. Since our product page, GH labels, all have search as top-level, I tried to keep it parallel.  https://www.medplum.com/products

Also, want try to avoid 3-level hierarchy where possible.

**Comment by reshmakh** [comment]
Sorry for weighing in late here.  @rahul1 - search is in the product ontology https://www.medplum.com/products#search

I neglected to make it a top level item (pure oversight) when refactoring the docs in Sept.  Possible to create the heading?

**Comment by reshmakh** [comment]
There is already a base document https://www.medplum.com/docs/search - it's just not in the side nav.

**Comment by codyebberson** [comment]
@rahul1 @reshmakh 

> I was trying to follow our product ontology. Since our product page, GH labels, all have search as top-level, I tried to keep it parallel. https://www.medplum.com/products

Got it, this makes sense.

> There is already a base document https://www.medplum.com/docs/search - it's just not in the side nav.

Rahul did exactly that in this PR.

This all lgtm 👍

**Review by codyebberson — APPROVED** [review]

**Pull request merged**
