### PR TITLE
Added a copy button to copy the resource ID on the resource page

### PR DESCRIPTION
**Pull request by Abi-Liu**
This PR adds a copy button to the resource ID on the resource page - https://github.com/medplum/medplum/issues/2606

### CODE REVIEW

**Comment by rahul1** [comment]
Hi @Abi-Liu , it seems like you're re-using the same branch from your previous PR: https://github.com/medplum/medplum/pull/2614

Best practice would be to create a new branch for this PR, with only the 1 commit `0a5b2b934ea5d7af87965687f76cf0d8fd8a5bc4`

**Comment by Abi-Liu** [comment]
Oh oops, I forgot to change the branch. Should I submit another PR in a newly created branch?

**Comment by codyebberson** [comment]
> Oh oops, I forgot to change the branch. Should I submit another PR in a newly created branch? @rahul1

Hi @Abi-Liu 

If you're comfortable using `git rebase`, that's the "right" way to do it.  Using `git rebase` can be frustrating though, so proceed with caution.  See here: https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-onto-remote-master

You can also do the simple / "brute force" strategy where you create a new branch, and manually copy the files over.

It's up to you.  No worries if you create a new PR and discard this one.

Thanks!

**Comment by Abi-Liu** [comment]
Sounds good! Just fixed it. Gonna submit another PR now.

**Pull request closed without merging**
