### PR TITLE
Embed storybook in docusaurus

### PR DESCRIPTION
**Pull request by rahul1**

### CODE REVIEW

**Review by codyebberson — COMMENTED** [review]
Nice

In preparation for some of the docs/www work, I setup https://storybook.medplum.com/ for Storybook -- thoughts on using that?

**Comment by rahul1** [comment]
(Discussed offline)
@codyebberson Yeah I'm down to point to wherever, we just need to make sure we don't run into any cross-domain issues with `www.medplum.com/docs` trying to render an iframe with content from `storybook.medpum.com`

**Comment by codyebberson** [comment]
> (Discussed offline) @codyebberson Yeah I'm down to point to wherever, we just need to make sure we don't run into any cross-domain issues with `www.medplum.com/docs` trying to render an iframe with content from `storybook.medpum.com`

docs.medplum.com CSP allows "*.medplum.com" in frames

storybook.medplum.com currently does not have a CSP

So it should work out of the box.

We will still need the special case for localhost

**Comment by rahul1** [comment]
SGTM I'll make the change

**Review by codyebberson — APPROVED** [review]

**Pull request merged**
